# Generated by Django 3.1.7 on 2021-03-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('person', 'group')},
        ),
    ]
